### ISSUE TITLE
Capitalization of CloudTasks headers

### ISSUE THREAD

**Issue by solsticedhiver** [aertje/cloud-tasks-emulator#18]
It's just a **very minor issue**, but why not use the exact capitalization for the X-CloudTaks-* headers ?

    X-CloudTasks-QueueName
    X-CloudTasks-TaskName
    X-CloudTasks-TaskRetryCount
    X-CloudTasks-TaskExecutionCount
    X-CloudTasks-TaskETA

instead of

    X-Cloudtasks-Queuename
    X-Cloudtasks-Taskname
    X-Cloudtasks-Taskretrycount
    X-Cloudtasks-Taskexecutioncount
    X-Cloudtasks-Tasketa

**Comment by aertje** [comment]
Sounds good, feel free to raise a PR!

**Comment by solsticedhiver** [comment]
I tried somehting like that:

```
diff --git a/task.go b/task.go
index 4ed1bbf..e05bed3 100644
--- a/task.go
+++ b/task.go
@@ -305,11 +305,12 @@ func dispatch(retry bool, taskState *tasks.Task) int {
 
        // Headers as per https://cloud.google.com/tasks/docs/creating-http-target-tasks#handler
        scheduled, _ := ptypes.Timestamp(taskState.GetScheduleTime())
-       req.Header.Set("X-CloudTasks-QueueName", nameParts.queueId)
-       req.Header.Set("X-CloudTasks-TaskName", nameParts.taskId)
-       req.Header.Set("X-CloudTasks-TaskExecutionCount", fmt.Sprintf("%v", taskState.GetResponseCount()))
-       req.Header.Set("X-CloudTasks-TaskRetryCount", fmt.Sprintf("%v", taskState.GetDispatchCount()-1))
-       req.Header.Set("X-CloudTasks-TaskEta", fmt.Sprintf("%f", float64(scheduled.UnixNano())/1e9))
+       // add header values using map operations to keep the capitalization
+       req.Header["X-CloudTasks-QueueName"] = []string{nameParts.queueId}
+       req.Header["X-CloudTasks-TaskName"] = []string{nameParts.taskId}
+       req.Header["X-CloudTasks-TaskExecutionCount"] = []string{fmt.Sprintf("%v", taskState.GetResponseCount())}
+       req.Header["X-CloudTasks-TaskRetryCount"] = []string{fmt.Sprintf("%v", taskState.GetDispatchCount()-1)}
+       req.Header["X-CloudTasks-TaskETA"] = []string{fmt.Sprintf("%f", float64(scheduled.UnixNano())/1e9)}
 
        resp, err := client.Do(req)
        if err != nil {

```
from https://stackoverflow.com/a/26352765/283067

It did not work. I don't know golang, and if you have to fight against the language to get what you want, I am giving up.

**Comment by aertje** [comment]
No problem, I can get to it at some point.

**Comment by acoulton** [comment]
Whoops, I never even spotted that. Sorry! I think partly because I was comparing to the headers captured from a real dispatch to on webhook.site, and they are all displayed as entirely lowercase - not sure if that's been done at the display end or if Google actually sent them like that...

I've just had a quick play and I've not been able to bypass the normalisation either, I've only really started writing go this week so probably missing something!

I guess there's value in strictly matching what Google send. That said, HTTP header keys are officially case-insensitive (e.g. [RFC7230 - 3.2](https://tools.ietf.org/html/rfc7230#section-3.2). Indeed the newer HTTP/2 [RFC 7540 - 8.1.2](https://tools.ietf.org/html/rfc7540#section-8.1.2) says:

> Just as in HTTP/1.x, header field names are strings of ASCII characters that are compared in a case-insensitive fashion.  However, header field names MUST be converted to lowercase prior to their encoding in HTTP/2.  A request or response containing uppercase header field names MUST be treated as malformed

So if anyone's actually affected by the emulator incorrectly capitalizing things, that's arguably a bug in their implementation.
